config/routes.rb
Rails.application.routes.draw do
  resources :declarations
  resources :reviews
  resources :professors
  resources :admin_user_mfa_session, only: [:new, :create]
  root to: 'professors#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(admin_user)
    admin_user ||= AdminUser.new
    if admin_user.role == 'admin'
      can :manage, :all
      can :update, :all
    elsif admin_user.role=='user'
      can :read, :all
      cannot :manage, Professor
      can :create, Review
      can :read, Review
      can :update, Review
      can :destroy, Review
    elsif admin_user.role=='banned'
      can :read, :all
      cannot :create, :all
      cannot :destroy, :all
      cannot :update, :all
    else
      can :read, :all
      cannot :create, Review
      cannot :create, Professor
      cannot :create, Declaration
      cannot :update, Review
      cannot :update, Professor
      cannot :update, Declaration
      cannot :destroy, Review
      cannot :destroy, Professor
      cannot :destroy, Declaration    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  acts_as_google_authenticated :lookup_token => :mfa_secret,
                               :encrypt_secrets => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  delegate :can?, :cannot?, :to => :ability
  has_one :review
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable, :trackable, :registerable,
         :confirmable

  ADMIN='admin'
  USER='user'
  BANNED='banned'
  ROLES ={ADMIN=>'admin',USER =>'user', BANNED=>'banned' }

  def ability
    @ability ||= Ability.new(self)
  end
end

app/models/admin_user_mfa_session.rb
class AdminUserMfaSession <  GoogleAuthenticatorRails::Session::Base
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/declaration.rb
class Declaration < ApplicationRecord
  has_many_attached :documents
  has_many_attached :pictures

  DECLARATIONS='declarations'
  TO_ENROLLEE='to enrollee'
  TO_STUDENTS='to students'
  TO_GRADUATES='to graduates'
  BELONGS_TO_PAGE ={DECLARATIONS => 'declarations',
  TO_ENROLLEE => 'to enrollee',
  TO_STUDENTS => 'to students',
  TO_GRADUATES => 'to graduates' }

end

app/models/professor.rb
class Professor < ApplicationRecord
  has_one_attached :image
  has_many_attached :documents
  validates :name, presence: true
  validates :position, presence: true
  validates :cabinet, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :admin_user
  validates :title, presence: true
  validates :rating, presence: true,
            numericality: {:less_than_or_equal_to => 5, :greater_than => 0}
end

app/controllers/admin_user_mfa_session_controller.rb
class AdminUserMfaSessionController < ApplicationController
  def new
    @skip_header_and_footer = true
    @current_admin_user = current_admin_user
    current_admin_user.google_secret_value if current_admin_user.set_google_secret
  end

  def create
    admin_user = current_admin_user
    admin_user.mfa_secret = params[:auth][:mfa_code]
    admin_user.save!
    if admin_user.google_authentic?(params[:auth][:mfa_code])
      AdminUserMfaSession.create(admin_user)
      redirect_to '/admin'
    else
      flash[:error] = 'Wrong code'
      render :new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def after_sign_in_path_for(admin_users)
    root_path
  end

  def after_sign_out_path_for(admin_users)
    root_path
  end

  def authenticate_admin_user!
    raise SecurityError unless current_admin_user && current_admin_user.role=='admin'
  end

  rescue_from SecurityError do |exception|
    redirect_to root_path
  end

  def current_ability
    @current_ability ||= Ability.new(current_admin_user)
  end
end

app/controllers/declarations_controller.rb
class DeclarationsController < InheritedResources::Base

  def index
    belongs_to_page = params[:belongs_to_page]
    @declarations = Declaration.where(belongs_to_page: belongs_to_page)
  end

  private

    def declaration_params
      params.require(:declaration).permit(:title, :body, :belongs_to_page,
                                          pictures: [], documents: [])
    end

end

app/controllers/professors_controller.rb
class ProfessorsController < InheritedResources::Base

  def view
    @professor = Professor.find(params[:id])
  end

  def index
    @professors = Professor.all
  end

  def show
    @professor = Professor.find(params[:id])
  end

  private

    def professor_params
      params.permit(:name, :position, :cabinet, :post_address, :email, :publications, :researches, :courses)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base

  def new
      @review = Review.new
  end

  def index
    @reviews = Review.all
  end

  def create
    if can? :create, Review
    @review = Review.new(review_params)
    @review.admin_user_id = current_admin_user.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to reviews_path, notice: 'Review was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  def update
    if can? :update, Review
      @review = Review.find params[:id]
      respond_to do |format|
        if @review.update(review_params)
          format.html { redirect_to @review, notice: 'Review was successfully updated.' }
          format.json { render :show, status: :ok, location: @review }
        else
          format.html { render :edit }
          format.json { render json: @review.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private

    def review_params
      params.require(:review).permit(:title, :body, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/declarations_helper.rb
module DeclarationsHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin_user_mfa_session/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("itas") %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>
</head>
<div>
  <% if flash[:error] %>
      <div>
        <ul>
          <%= flash[:error] %>
        </ul>
      </div>
  <% end %>
</div>
<div>
  <% if @current_admin_user.sign_in_count <= 1 %>
  <div>
    <h2><%= t("scan_qr") %></h2>
     <%= image_tag(@current_admin_user.google_qr_uri) %>
  </div>
  <div>
    <% end %>
    <%= form_tag admin_user_mfa_session_index_path, method: :post do %>
        <p><%= t("auth_code") %></p>
        <%= text_field :auth, :mfa_code, autofocus: true %>
        <%= submit_tag 'authenticate' %>
    <% end %>
  </div>
</div>

app/views/declarations/index.html.erb
<div class="declarations-body">
<p id="notice"><%= notice %></p>
<% if request.query_parameters['belongs_to_page'] == 'declarations' %>
  <h3 style = "text-align: center"><%= t('declarations') %></h3>
<% elsif request.query_parameters['belongs_to_page'] == 'to students' %>
  <h3 style = "text-align: center"><%= t('to_students') %></h3>
<% elsif request.query_parameters['belongs_to_page'] == 'to enrollee' %>
  <h3 style = "text-align: center"><%= t('to_enrollee') %></h3>
<% elsif request.query_parameters['belongs_to_page'] == 'to graduates' %>
  <h3 style = "text-align: center"><%= t('to_graduates') %></h3>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @declarations.each do |declaration| %>
      <div class="declarations-text">
        <tr>
          <p><%= link_to "#{declaration.title}", declaration_path(declaration.id) %></p>
          <p><%= declaration.body %></p>
          <td valign="top">
            <div class="declarations-images">
            <% if declaration.pictures.attached? %>
                <% declaration.pictures.each do |picture| %>
                    <%= image_tag (picture), :class => 'declaration_images' %>
                <% end %>
            <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <% if declaration.documents.attached? %>
                <% declaration.documents.each do |document| %>
                    <p><%= link_to "#{document.filename}", rails_blob_path(document, disposition: 'attachment') %></p>
                <% end %>
            <% end %>
            <hr size="1" width="98%" color="#01a0e2">
          </td>
        </tr>
      </div>
  <% end %>
  </tbody>
</table>
<br>
</div>

app/views/declarations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_declaration_path(@declaration) %> |
<%= link_to 'Back', declarations_path %>

app/views/layouts/_footer.html.erb
<div class="footer-margin">
  <footer class="card-footer bg-light footer-font-style text-muted sticky-bottom footer-position">
  <strong><%=t('contact_us')%></strong>
  <i class="fa fa-phone"> +375 17 293-88-23</i>
  <i class="fas fa-home mr-3"><%= t('address') %></i>
  <i class="fas fa-envelope mr-3"> kafitas@bsuir.by</i>
</footer>
</div>

app/views/layouts/_header.html.erb
<div class="header-margin">
<nav class="main-header navbar navbar-expand navbar-white border-bottom fixed-top border-primary ">
  <ul class="navbar-nav">
    <% random_number = rand(1..6) %>
    <% case random_number %>
    <% when 1 %>
      <%= image_tag ("logo.jpg")%>
    <% when 2 %>
        <%= image_tag ("logo_dadaism.jpg")%>
    <% when 3 %>
        <%= image_tag ("logo_defolation.jpg")%>
    <% when 4 %>
        <%= image_tag ("logo_fauvism.jpg")%>
    <% when 5 %>
        <%= image_tag ("logo_magick_cube.jpg")%>
    <% when 6 %>
        <%= image_tag ("logo_sponge.jpg")%>
    <% end %>
  <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('professors'), professors_path(), class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('declarations'), declarations_path(belongs_to_page: 'declarations'), class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('to_enrollee'), declarations_path(belongs_to_page: 'to enrollee'), class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('to_students'), declarations_path(belongs_to_page: 'to students'), class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('to_graduates'), declarations_path(belongs_to_page: 'to graduates'), class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t('reviews'), reviews_path, class: "btn", style: 'color:#01a0e2;'%>
    </li>
    <% if request.query_parameters['locale'] == 'en' %>
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to t('locale'), { :locale=>'ru'}, class: "btn", style: 'background-color: #01a0e2; color:#ffffff;'%>
      </li>
    <% elsif request.query_parameters['locale'] == 'ru' %>
      <li class="nav-item d-none d-sm-inline-block">
        <%= link_to t('locale'), { :locale=>'en'}, class: "btn", style: 'background-color: #01a0e2; color:#ffffff;'%>
      </li>
    <% end %>
    <% if !current_admin_user %>
      <li class="nav-item d-none d-sm-inline-block ">
        <%= link_to t('sign_in'), new_admin_user_session_path, class: "btn ", style: 'position:fixed; top:10px; right:10px; background-color: #01a0e2; color:#ffffff;'%>
      </li>
    <% elsif current_admin_user && current_admin_user.role == 'admin' %>
      <li class="nav-item d-none d-sm-inline-block ">
        <%= link_to t('admin'), admin_admin_users_path, class: "btn ", style: 'position:fixed; top:10px; right:10px; background-color: #01a0e2; color:#ffffff;'%>
      </li>
    <% else %>
      <li class="nav-item d-none d-sm-inline-block ">
        <%= link_to t('sign_out'), destroy_admin_user_session_path, class: "btn ", style: 'position:fixed; top:10px; right:10px; background-color: #01a0e2; color:#ffffff;'%>
      </li>
    <% end %>

  </ul>
</nav>
<div style = "position:fixed; top:10px; right:10px; background-color: #01a0e2">

  </ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag %>
<head>
  <title>ITAS</title>
  <%= csrf_meta_tags %> <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/6d90f39943.js"></script>
</head>
<body class="sidebar-mini">
  <div class="wrapper">
    <%= render partial: "layouts/header" %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
  </div>
</body>
<div class="footer">
  <%= render partial: "layouts/footer" %>
</div>
</html>

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/index.html.erb
<h3 style = "text-align: center"> <%= t('professors') %> </h3>
<div style = "position:absolute; top:150px; left:30px;">
<table cellpadding="6" cellspacing="0">
  <tbody>
  <tr>
    <% @professors.each do |professor| %>
      <tr>
        <td valign="top">
          <% if professor.image.attached? %>
              <%= image_tag (professor.image), :class => 'professor_image' %>
          <% end %>
        </td>
        <td valign="middle" width="100%">
          <b><%= professor.name %></b>
          <br><%= professor.position %>
          <br><%= link_to t('Personal page'), professor_path(professor.id) %>
          <br><%= t('auditorium') + professor.cabinet%>
          <br><%= t('phone_number') + professor.phone_number %>
          <br><%= "E-mail: #{professor.email}" %>
        </td>
      </tr>
        <tr>
          <td colspan="2" valign="top">
            <% if professor.courses != ''  %>
              <p>
                <b><br><%= t('courses') %></b>
                <%= simple_format(professor.courses) if professor.courses %>
                <br>
              </p>
            <% end %>
            <% if professor.researches != ''  %>
              <p>
                <b><br><%= t('researches') %></b>
                <%= professor.researches %>
                <br>
              </p>
            <% end %>
            <% if professor.publications != ''  %>
              <p>
                <b><br><strong> <%= t('publications') %> </strong></b>
                <%= simple_format(professor.publications) if professor.publications %>
                <br>
              </p>
            <% end %>
            <hr size="1" width="98%" color="#01a0e2">
          </td>
        </tr>
    <% end %>
  </tr>
  </tbody>
</table>
</div>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="professor-show">
<p>
  <strong><%= @professor.name %></strong>
</p>

<p>
  <%= @professor.position %>
</p>

<p class="professor-image">
  <%= image_tag (@professor.image), :class => 'professor_image' %>
</p>

<p>
  <% t('auditorium') %>
  <%= @professor.cabinet %>
</p>

<p>
  <% t('phone_number') %>
  <%= @professor.phone_number %>
</p>

<p>
  <% 'e-mail: ' %>
  <%= @professor.email %>
</p>

<p>
  <% t('declarations') %>
  <% if @professor.documents.attached? %>
      <% @professor.documents.each do |document| %>
        <p><%= link_to "#{document.filename}", rails_blob_path(document, disposition: 'attachment') %></p>
    <% end %>
<% end %>
</p>
</div>

app/views/reviews/_form.html.erb
<div class="review-form">
<%= simple_form_for @review do |f| %>

    <%= f.input :title %>

    <%= f.input :body %>

    <%= f.input :rating, collection: [1, 2, 3, 4, 5], prompt: :translate %>

    <%= f.button :submit, class: "btn-primary" %>

    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>

<% end %>
</div>

app/views/reviews/edit.html.erb
<% if current_admin_user && !current_admin_user.review %>
    <%= controller.redirect_to new_review_path %>
<% end %>

<% if current_admin_user.role == 'banned' || !current_admin_user %>
    <%= controller.redirect_to root_path %>
<% end %>

<h1><% t('editing_review') %></h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div class="review-text">
<p id="notice"><%= notice %></p>

<h3 style = "text-align: center"><% t('reviews') %></h3>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>

        <tr>
          <td><strong><%= "#{review.title.upcase}  " %></strong></td>
        </tr>
      <tr>
        <td>
          <% review.rating.times do %>
            <span class="fa fa-star checked star-a"></span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td class="review-email">
          <%= review.admin_user().email %>
        </td>
      </tr>
      <tr>
        <td><%= review.body %></td>
      </tr>
      <tr>
        <td><hr size="1" width="98%" color="#01a0e2"></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_admin_user && current_admin_user.role != 'banned' && !current_admin_user.review %>
    <%= link_to t('new_review'), new_review_path, class: "btn ", style: 'background-color: #01a0e2; color:#ffffff;' %>
<% elsif current_admin_user && current_admin_user.review %>
    <%= link_to t('edit_review'), edit_review_path(current_admin_user.review.id), class: "btn ", style: 'background-color: #01a0e2; color:#ffffff;' %>
<% end %>
</div>

app/views/reviews/new.html.erb
<% if current_admin_user && current_admin_user.review  %>
    <%= controller.redirect_to edit_review_path(current_admin_user.review.id) %>
<% end %>

<% if current_admin_user.role == 'banned' %>
    <%= controller.redirect_to root_path %>
<% end %>

<% unless current_admin_user %>
    <%= controller.redirect_to root_path %>
<% end %>

<h3 style = "text-align: center"><% t('new_review') %></h3>

<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>